format = '''
$username@$hostname $directory $os $time $git_branch
$sudo$character
'''
right_format = '''
$cmd_duration
'''

add_newline = true
command_timeout = 60000

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol = "🔓"

[hostname]
disabled = false
ssh_only = false
style = "#FFB86C"
format = "[$hostname]($style)"

[character]
success_symbol = '[➜](#BD93F9)'
error_symbol = "[➜](#FF5555)"

[directory]
format = "in [$path]($style)"
style = "#F1FA8C"

[os]
disabled = false
style = "#50FA7B"
format = "on [($name $codename $version)]($style)"

[time]
disabled = false
style = "#8BE9FD"
format = 'at [$time]($style)'

[username]
disabled = false
show_always = true
aliases = { "<my-ldap-email>" = "mcs" }
style_user = "#FF79C6"
format = "[$user]($style)"

[cmd_duration]
disabled = false
style = "#FFB86C"
format = "[$duration]($style)"
